#!/bin/python3

import math
import os
import random
import re
import sys

def flippingMatrix(matrix):
    # Write your code here
    sum_new = 0
    n=len(matrix)//2
    for i in range(n):
        for j in range(n):
            sum_new += max(matrix[i][j], matrix[i][(2*n)-j-1], matrix[(2*n)-i-1][j], matrix[(2*n)-i-1][(2*n)-j-1])
    
    return sum_new

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        n = int(input().strip())

        matrix = []

        for _ in range(2 * n):
            matrix.append(list(map(int, input().rstrip().split())))

        result = flippingMatrix(matrix)

        fptr.write(str(result) + '\n')

    fptr.close()
