#!/bin/python3

import math
import os
import random
import re
import sys


def countingValleys(steps, path):
    res=[]                # initializing an array
    c=s=0        
    for i in path:
        if i=="U":        #checking if the element is U
            s=s+1         # then s+1
        else:
            s=s-1         # if not then s-1
        res.append(s)     # making a new list which stores the values of s
    for j in range(len(res)):
        if res[j]==0 and res[j-1]<0:   # checking if the element is 0 and the previous element is negative
            c=c+1
    return c    # returning the count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
