#!/bin/python3

import math
import os
import random
import re
import sys



def countingSort(arr):
    # Write your code here
    result=[0]*100  # initializing the result array with 0's
    
    for i in arr:        
        result[i] = result[i]+1   # for each element the number of times it appears it gets appended in that position
    return result
         
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
