#!/bin/python3

import math
import os
import random
import re
import sys

def diagonalDifference(arr):

    n=len(arr)  # calculating the length of the array
    result,sum1,sum2=0,0,0
    
    for i in range(n):
        sum1 += arr[i][i]    # sum of the left diagonal
        sum2 += arr[i][n-1-i] # sum of the right diagonal
    result = abs(sum1-sum2)
    return result
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
