#!/bin/python3

import math
import os
import random
import re
import sys

def marsExploration(s):
    original_message = "SOS"*(int(len(s)/3))
    n=list(s)
    c=0
    for i in range(len(n)):
        if n[i] !=original_message[i]:
            c=c+1
    return c

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
