#!/bin/python3

import math
import os
import random
import re
import sys

def divisibleSumPairs(n, k, ar):
    # Write your code here
    c=0  #initializing the counter variable
    
    for i in range(0,n-1):
        for j in range(0,n):
            # Checking the condition if sum of the pair is divisible by k
            # And i<j            
                if (ar[i]+ar[j])%k==0 and i<j:
                    # number of times the condition is true
                    c=c+1
    return c      

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    ar = list(map(int, input().rstrip().split()))

    result = divisibleSumPairs(n, k, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
