#!/bin/python3

import math
import os
import random
import re
import sys

def miniMaxSum(arr):
    # Write your code here
    arr.sort()
    n=len(arr)
    s,t=0,0
    for i in range(0,n-1):
        s=s+arr[i]
    for i in range(1,n):
        t=t+arr[i]
    print(str(s)+" "+str(t))

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
